resolver: lts-19.4
packages:
- .
ghc-options:
  "$locals": -Weverything -Werror -Wno-safe -Wno-unsafe
             -Wno-missing-safe-haskell-mode -Wno-implicit-prelude
             -Wno-missing-local-signatures -Wno-missing-import-lists
             -Wno-missing-kind-signatures

nix:
  shell-file: nix/stack.nix
